### ISSUE TITLE
All papers are self citations

### ISSUE THREAD

**Issue by andrewjpage** [warrenlr/RAILS#3]
All of the papers you cite are self citations. Consider perhaps citing papers you havent been involved in (theres plenty to choose from).  For example, you could cite other gap closing applications such as GapFiller and IMAGE.

https://genomebiology.biomedcentral.com/articles/10.1186/gb-2012-13-6-r56

https://genomebiology.biomedcentral.com/articles/10.1186/gb-2010-11-4-r41

**Comment by warrenlr** [comment]
fixed
